### ISSUE TITLE
Better error message when linter binary cannot be found

### ISSUE THREAD

**Issue by trapgate** [steelbrain/atom-linter#84]
I installed linter-pep8 to work on some python files, and didn't realize I had to install pep8 separately. When this happens atom-linter pops up a red message with this text:

```
Error: spawn pep8 ENOENT
    at exports._errnoException (util.js:837:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at doNTCallback2 (node.js:441:9)
    at process._tickCallback (node.js:355:17)
```

Can this message be replaced with a clearer error message? Something like, 'linter binary for "linter-xxx" plug-in not found.'

**Comment by steelbrain** [comment]
I have been thinking about this for quite a while

**Comment by adamboche** [comment]
Problem still exists

**Comment by steelbrain** [comment]
A fix is up in https://github.com/steelbrain/atom-linter/pull/149
